name: Sync with upstream
on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch: {}

jobs:
  rebase-sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/neovim/neovim.git
          git fetch upstream
      - name: Rebase onto upstream
        run: |
          git rebase upstream/master
      - name: Push changes
        run: git push --force --tags
